### PR TITLE
US69736 - Search helper cursor

### PR DESCRIPTION
**Pull request by capajon**
Will merge to scss and wc branches after

### CODE REVIEW

**Comment by capajon** [comment]
@dlockhart Maybe take a quick look in case this change isn't as simple as I think it is. :)

I'll also make a patch # release after merge.

**Comment by dlockhart** [comment]
@capajon: yeah I think that's all you need to fix the second part of the issue. Not sure what's causing the first part (the extra space at the beginning).

**Comment by capajon** [comment]
@dlockhart The first part seemed to 'solve itself' from the time the defect was logged to when I took it.  Still seems okay.  I'm willing to just accept that though I am slightly curious. :)

**Comment by capajon** [comment]
Thanks for catching this in the Mac environment.  The accepted answer here (http://stackoverflow.com/questions/11127891/how-can-i-get-rid-of-horizontal-padding-or-indent-in-html5-search-inputs-in-webk) did take care of things easily enough. :)

**Comment by dlockhart** [comment]
@capajon np, looks good!

**Pull request merged**
